### ISSUE TITLE
Parallel packet analysis

### ISSUE THREAD

**Issue by ba11b0y** [darshkpatel/NetNetra#1]
Parse packet stream, push serialized packet object in go channel and parallely read.

Refs:

 - https://godoc.org/github.com/google/gopacket
 - https://github.com/google/gopacket/blob/master/packet.go

**Comment by ba11b0y** [comment]
This [commit](https://github.com/darshkpatel/NetNetra/commit/9418ec559662723ce3493866a1b6c6e619f03e62) adds the packet capture functionality with channels.
Apologies for not creating a PR, will keep that in mind from now.
Thoughts @darshkpatel ?

**Comment by darshkpatel** [comment]
Looks good, 
let's settle upon a proper project structure so that maintenance is easy

**Comment by darshkpatel** [comment]
This is done I guess?

**Comment by ba11b0y** [comment]
Yeah yeah

**Comment by darshkpatel** [comment]
Closing
