### ISSUE TITLE
Discuss packet data to be indexed in ElasticSearch

### ISSUE THREAD

**Issue by ba11b0y** [darshkpatel/NetNetra#5]
The primary [packet object](https://github.com/google/gopacket/blob/0ad7f2610e344e58c1c95e2adda5c3258da8e97b/packet.go#L56) contains a lot of info about each packet.
Let's discuss what all we can index.

**Comment by darshkpatel** [comment]
We can index all the data from the last layer I believe, ```DecodingLayerParser``` takes about 10% of the original time to decode a specific layer.

Ref: https://godoc.org/github.com/google/gopacket#hdr-Fast_Decoding_With_DecodingLayerParser

**Comment by ba11b0y** [comment]
This seems the way to go.
Mind giving it a shot?

**Comment by darshkpatel** [comment]
Sure, Will send a PR within the day

**Comment by darshkpatel** [comment]
Ref: Discussion at #6
